version: '3'

vars:
  BUILD_DIR: build
  PROJECT_NAME: irccloud-watcher
  VERSION: 1.0.0

tasks:
  # Core build task - depends on tests and linting
  build:
    desc: Build the project
    deps: [test, lint]
    cmds:
      - task: build-go

  # Linux-specific build
  build-linux:
    desc: Build for Linux
    deps: [test, lint]
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - task: build-go

  # CI build with proper test coverage and linting
  build-ci:
    desc: Build for CI/CD
    deps: [test-ci, lint]
    cmds:
      - task: build-go

  # Test tasks
  test:
    desc: Run tests
    cmds:
      - task: test-go

  test-ci:
    desc: Run tests with coverage for CI
    cmds:
      - task: test-go-ci

  # Linting tasks
  lint:
    desc: Lint code
    cmds:
      - task: lint-go

  # Clean build artifacts
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - mkdir -p {{.BUILD_DIR}}

  # Go-specific tasks
  build-go:
    desc: Build Go project
    cmds:
      - gofmt -w -s -e .
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.PROJECT_NAME}} ./cmd/irccloud-watcher

  test-go:
    desc: Run Go tests
    cmds:
      - go test -v ./...

  test-go-ci:
    desc: Run Go tests with coverage for CI
    cmds:
      - go test -tags=ci -cover -v ./...

  lint-go:
    desc: Lint Go code
    cmds:
      - go fmt ./...
      - go vet ./...
      - golangci-lint run

  # Development tasks
  dev:
    desc: Start development server
    cmds:
      - go run ./cmd/irccloud-watcher
